### ISSUE TITLE
Trebuie adaugat totalHoursWorked in grila de pontaj

### ISSUE THREAD

**Issue by drupanim** [drupanim/ascontihrm#11]

**Comment by drupanim** [comment]
Am adaugat numarul de ore lucrate pe fiecare angajat/ santier in grila de pontaj. sunt calculate automat la fiecare initializare de grid.

**Comment by drupanim** [comment]
![image](https://user-images.githubusercontent.com/10667267/63585980-fe1cf900-c5a8-11e9-86c7-b54345d8eb71.png)

**Comment by edracaz** [comment]
Pai si daca modifici pontaj, se updateaza auto si total? Solutia e mai jos pentru asta:

1. trebuie adaugata urmatoarea coloana (dupa coloana field: 'timp'): 
{
            field: 'timpTotal',
            pinned: 'left',
            editable: false,
            headerName: 'Total',
            type: 'totalColumn',
            // we use getValue() instead of data.a so that it gets the aggregated values at the group level
            valueGetter: function(params) {
              console.log(params)
              var fieldTotal = 0;
              for (i = 1; i <= moment(monthToRenderString, "YYYY-MM").daysInMonth(); i++) {
                  fieldTotal += params.getValue("day_" + i);
              }
              if (typeof params.data === 'undefined') {
                return fieldTotal
              } else {
                return '';
              }
            }
        }

2. dupa 'columnDefs: columnDefs' trebuie adaugat urm:

    columnTypes: {
        totalColumn: {
          cellRenderer:'agAnimateShowChangeCellRenderer', cellClass: 'number-cell'
        }
    },
